version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin*2024
    ports:
      - 27017:27017
    volumes:
      - ~/app/mongo:/data/db